{
  "hash": "143991c0bb382a58e61d8ebdf48b45f6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Predictive Pricing Model\"\n---\n\n\n\n## Overview\n\nA multiple regression model predicting sale prices using the strongest drivers identified in previous analysis.\n\n---\n\n## The Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create derived variables and remove missing values\names_complete <- ames %>%\n  mutate(\n    Age_at_Sale = Yr.Sold - Year.Built\n  ) %>%\n  filter(!is.na(Garage.Area))\n\n# Fit model (removed Has_Central_Air per TA feedback - high p-value)\nmodel <- lm(SalePrice ~ Gr.Liv.Area + Overall.Qual + Garage.Area + \n                       Age_at_Sale,\n           data = ames_complete)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = SalePrice ~ Gr.Liv.Area + Overall.Qual + Garage.Area + \n    Age_at_Sale, data = ames_complete)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-416042  -22223   -2133   18041  293536 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -62484.075   4618.922  -13.53   <2e-16 ***\nGr.Liv.Area      55.816      1.799   31.03   <2e-16 ***\nOverall.Qual  23742.947    763.998   31.08   <2e-16 ***\nGarage.Area      60.779      4.257   14.28   <2e-16 ***\nAge_at_Sale    -380.758     30.550  -12.46   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 38320 on 2924 degrees of freedom\nMultiple R-squared:  0.7703,\tAdjusted R-squared:  0.7699 \nF-statistic:  2451 on 4 and 2924 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Model Performance:**\n- **R² = 0.77** (explains 77% of price variation)\n- **RMSE = $38,290** (typical prediction error)\n\n**Note on Has_Central_Air:** While Week 7's t-test showed central AC adds $84,562 in isolation, this effect disappears (p > 0.05) after controlling for quality, size, and age in the multiple regression. This suggests the AC premium is actually due to correlation with these other factors (newer, higher-quality homes have AC). Removing it improves model parsimony without reducing R².\n\n---\n\n## Key Coefficients\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef_table <- tidy(model, conf.int = TRUE) %>%\n  filter(term != \"(Intercept)\")\n\nkable(coef_table %>% select(term, estimate, conf.low, conf.high, p.value),\n      col.names = c(\"Variable\", \"Coefficient\", \"95% CI Low\", \"95% CI High\", \"P-value\"),\n      digits = c(0, 0, 0, 0, 4))\n```\n\n::: {.cell-output-display}\n\n\n|Variable     | Coefficient| 95% CI Low| 95% CI High| P-value|\n|:------------|-----------:|----------:|-----------:|-------:|\n|Gr.Liv.Area  |          56|         52|          59|       0|\n|Overall.Qual |       23743|      22245|       25241|       0|\n|Garage.Area  |          61|         52|          69|       0|\n|Age_at_Sale  |        -381|       -441|        -321|       0|\n\n\n:::\n:::\n\n\n### Interpretation\n\n**Overall Quality:** Each 1-point increase = +$23,743 \n- Moving from quality 6 to 9 (3 points) = +$71,229\n\n**Living Area:** Each 100 sq ft = +$5,582\n\n**Garage Area:** Each 100 sq ft garage = +$6,078\n\n**Age:** Each year older = −$381\n- A 30-year-old home vs. new = −$11,423\n\n**All coefficients are statistically significant (p < 0.001)**\n\n---\n\n## Model Diagnostics (Assumptions Check)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(model)\n```\n\n::: {.cell-output-display}\n![](pricing-model_files/figure-html/diagnostics-1.png){width=1152}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n**Assessment:**\n- ✓ **Linearity:** Met (residuals vs fitted is flat)\n- ⚠ **Homoscedasticity:** Mild violation (fanning at high prices)\n- ✓ **Normality:** Reasonably met (Q-Q plot good in center)\n- ✓ **No multicollinearity:** VIF < 5 for all predictors\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Variance Inflation Factors (VIF):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVariance Inflation Factors (VIF):\n```\n\n\n:::\n\n```{.r .cell-code}\nvif_values <- vif(model)\nprint(vif_values)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Gr.Liv.Area Overall.Qual  Garage.Area  Age_at_Sale \n    1.648347     2.317251     1.670846     1.706491 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nAll VIF < 5: No multicollinearity concerns\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAll VIF < 5: No multicollinearity concerns\n```\n\n\n:::\n:::\n\n\n**Conclusion:** Model is valid for inference despite mild heteroscedasticity.\n\n---\n\n## Example Predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example homes\nexamples <- data.frame(\n  Gr.Liv.Area = c(1200, 1500, 2000, 2500),\n  Overall.Qual = c(5, 7, 8, 9),\n  Garage.Area = c(300, 400, 500, 600),\n  Age_at_Sale = c(40, 20, 10, 5)\n)\n\npredictions <- predict(model, newdata = examples, interval = \"prediction\")\n\nresult <- cbind(examples, \n                Predicted = predictions[,\"fit\"],\n                Lower_95 = predictions[,\"lwr\"],\n                Upper_95 = predictions[,\"upr\"])\n\nkable(result,\n      col.names = c(\"Living Area\", \"Quality\", \"Garage\", \"Age\",\n                    \"Predicted Price\", \"95% Lower\", \"95% Upper\"),\n      digits = 0)\n```\n\n::: {.cell-output-display}\n\n\n| Living Area| Quality| Garage| Age| Predicted Price| 95% Lower| 95% Upper|\n|-----------:|-------:|------:|---:|---------------:|---------:|---------:|\n|        1200|       5|    300|  40|          126213|     51044|    201382|\n|        1500|       7|    400|  20|          204136|    128965|    279308|\n|        2000|       8|    500|  10|          265673|    190482|    340863|\n|        2500|       9|    600|   5|          325305|    250072|    400539|\n\n\n:::\n:::\n\n\n**How to read this table:**\n- A 1,200 sq ft, quality-5 home, 40 years old predicts around $126,000\n- A 2,500 sq ft, quality-9 home, 5 years old predicts around $325,000\n- 95% prediction intervals show where we expect actual prices to fall\n\n---\n\n## Model Limitations\n\n1. **Less accurate for luxury homes** (>$300K) due to heteroscedasticity\n2. **Missing location effects** - neighborhood not included\n3. **Time-specific** - based on 2006-2010 market\n4. **Unexplained variance** - 23% of variation from other factors (likely location, lot characteristics, market timing)\n\n**Use case:** Baseline valuation; adjust for location and market conditions.\n\n---\n\n## Next Steps\n\nProceed to [Market Timing](timing.qmd) to understand when to buy or sell based on seasonal patterns and economic cycles.\n",
    "supporting": [
      "pricing-model_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}