{
  "hash": "b936e685d67f42c63b1707b35709a954",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"What Drives Home Prices?\"\n---\n\n\n\n## Overview\n\nThis analysis identifies which home features have the strongest impact on sale prices using:\n- **Correlation analysis** (Week 6)\n- **Hypothesis testing** (Week 7)\n- **ANOVA** (Week 8)\n\n---\n\n## Top Price Drivers (Correlation Analysis)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate key correlations\ncorrelations <- data.frame(\n  Feature = c(\"Overall Quality\", \"Living Area\", \"Garage Area\", \n              \"Basement Area\", \"Year Built\"),\n  Correlation = c(\n    cor(ames$Overall.Qual, ames$SalePrice),\n    cor(ames$Gr.Liv.Area, ames$SalePrice),\n    cor(ames$Garage.Area, ames$SalePrice, use = \"complete.obs\"),\n    cor(ames$Total.Bsmt.SF, ames$SalePrice, use = \"complete.obs\"),\n    cor(ames$Year.Built, ames$SalePrice)\n  )\n) %>%\n  arrange(desc(abs(Correlation)))\n\nkable(correlations, digits = 3,\n      caption = \"Top 5 Features Correlated with Sale Price\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 5 Features Correlated with Sale Price\n\n|Feature         | Correlation|\n|:---------------|-----------:|\n|Overall Quality |       0.799|\n|Living Area     |       0.707|\n|Garage Area     |       0.640|\n|Basement Area   |       0.632|\n|Year Built      |       0.558|\n\n\n:::\n:::\n\n\n**Key Finding:** Overall Quality (r = 0.80) and Living Area (r = 0.71) are the strongest predictors.\n\n### Visualization: Quality vs. Price\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ames, aes(x = factor(Overall.Qual), y = SalePrice)) +\n  geom_boxplot(fill = \"#3498db\", alpha = 0.7) +\n  stat_summary(fun = mean, geom = \"point\", shape = 23, \n               size = 3, fill = \"red\") +\n  scale_y_continuous(labels = dollar_format()) +\n  labs(title = \"Sale Price by Overall Quality Rating\",\n       subtitle = \"Red diamond = mean price for each quality level\",\n       x = \"Overall Quality (1 = Poor, 10 = Excellent)\",\n       y = \"Sale Price\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](price-drivers_files/figure-html/quality-price-1.png){width=960}\n:::\n:::\n\n\n---\n\n## Feature Impact: Hypothesis Tests\n\n### Central Air Conditioning\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the groups FIRST\nac_yes <- ames %>% filter(Central.Air == \"Y\") %>% pull(SalePrice)\nac_no <- ames %>% filter(Central.Air == \"N\") %>% pull(SalePrice)\n\n# Then run the t-test\nt_result <- t.test(ac_yes, ac_no)\n\ncat(\"Homes WITH Central Air: mean =\", dollar(mean(ac_yes)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHomes WITH Central Air: mean = $186,453 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Homes WITHOUT Central Air: mean =\", dollar(mean(ac_no)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHomes WITHOUT Central Air: mean = $101,890 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Difference:\", dollar(mean(ac_yes) - mean(ac_no)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference: $84,562.31 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P-value:\", format(t_result$p.value, scientific = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP-value: 8.784936e-88 \n```\n\n\n:::\n:::\n\n\n**P-value interpretation:**\n\nThe p-value of 8.784936e-88 means:\n\n- **If central air had NO effect** on price (null hypothesis true)\n- The probability of observing a difference of $84,562 or more extreme\n- **Is less than 0.001** (0.1%)\n\nIn other words: This result is so extreme that it's virtually impossible to have occurred by chance alone if AC truly didn't matter. We have **very strong evidence** that central air increases home values.\n\n**Statistical significance:** ✓ p < 0.001 (highly significant)  \n**Practical significance:** $84,562 difference is substantial (approximately 47% of median home price)\n\n---\n\n### Recent Construction (2000+)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create binary variable for recent construction\names <- ames %>%\n  mutate(Is_Recent = Year.Built >= 2000)\n\nrecent <- ames %>% filter(Is_Recent) %>% pull(SalePrice)\nolder <- ames %>% filter(!Is_Recent) %>% pull(SalePrice)\n\nt_result2 <- t.test(recent, older, alternative = \"greater\")\n\ncat(\"Recent homes (2000+): mean =\", dollar(mean(recent)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRecent homes (2000+): mean = $248,521 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Older homes (<2000): mean =\", dollar(mean(older)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOlder homes (<2000): mean = $156,097 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Difference:\", dollar(mean(recent) - mean(older)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference: $92,424.14 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P-value:\", format(t_result2$p.value, scientific = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP-value: 1.438068e-126 \n```\n\n\n:::\n:::\n\n\n**P-value interpretation:**\n\nThe p-value of 1.438068e-126 means:\n\n- **If construction year had NO effect** on price (null hypothesis true)\n- The probability of observing a difference of $92,424 or more extreme\n- **Is less than 0.001** (0.1%)\n\n**Finding:** Recently built homes (2000+) sell for **$92,424** more on average than older homes.\n\n**Statistical significance:** ✓ p < 0.001 (highly significant)  \n**Practical significance:** This $92K+ premium represents a 51% increase over the average older home price\n\n---\n\n## House Style Effect (ANOVA)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ANOVA test\nanova_result <- aov(SalePrice ~ House.Style, data = ames)\nanova_summary <- summary(anova_result)\n\ncat(\"ANOVA F-statistic:\", round(anova_summary[[1]][\"House.Style\", \"F value\"], 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nANOVA F-statistic: 35.04 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P-value:\", format(anova_summary[[1]][\"House.Style\", \"Pr(>F)\"], scientific = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP-value: 3.02871e-47 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n✓ House style DOES affect price (p < 0.001)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ House style DOES affect price (p < 0.001)\n```\n\n\n:::\n\n```{.r .cell-code}\n# Mean price by style\nstyle_summary <- ames %>%\n  group_by(House.Style) %>%\n  summarise(\n    Count = n(),\n    Mean_Price = mean(SalePrice),\n    .groups = 'drop'\n  ) %>%\n  arrange(desc(Mean_Price))\n\nkable(style_summary, \n      col.names = c(\"House Style\", \"Count\", \"Mean Price\"),\n      digits = 0)\n```\n\n::: {.cell-output-display}\n\n\n|House Style | Count| Mean Price|\n|:-----------|-----:|----------:|\n|2.5Fin      |     8|     220000|\n|2Story      |   873|     206990|\n|1Story      |  1481|     178700|\n|2.5Unf      |    24|     177158|\n|SLvl        |   128|     165527|\n|SFoyer      |    83|     143473|\n|1.5Fin      |   314|     137530|\n|1.5Unf      |    19|     109663|\n\n\n:::\n:::\n\n\n**P-value interpretation:**\n\nThe p-value < 0.001 from the ANOVA test means:\n\n- **If house style had NO effect** on price (all styles have same mean price)\n- The probability of observing differences this large between groups\n- **Is less than 0.1%**\n\n**Finding:** Two-story homes command highest prices (mean: ~$200K), while split-level/multi-level homes have lowest prices (mean: ~$140K).\n\n**Statistical significance:** ✓ p < 0.001 (highly significant)  \n**Practical significance:** $60K+ difference between highest and lowest style types\n\n---\n\n## Summary: Price Driver Rankings\n\n**Top 5 drivers (by effect size):**\n\n1. **Overall Quality** (r = 0.80) - Strongest predictor\n2. **Living Area** (r = 0.71) - Size matters\n3. **Recent Construction** (+$92K) - Buyers pay premium for new\n4. **Central Air** (+$85K) - Modern necessity\n5. **Garage Area** (r = 0.64) - Storage/parking valued\n\n**Actionable insight:** Focus on quality improvements over size additions for best ROI.\n\n---\n\n## Next Steps\n\nProceed to [Pricing Model](pricing-model.qmd) to build a multiple regression model that controls for these features simultaneously and quantifies their independent effects.\n",
    "supporting": [
      "price-drivers_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}